#!/usr/bin/env bash

# http://master.dl.sourceforge.net/project/mindreframerpackages/....
# remove osx files
find pkg/|grep .DS |xargs rm
# upload binaries folder
rsync --exclude='*.gitkeep' -rv pkg/ -e ssh mindreframer@frs.sourceforge.net:/home/frs/project/mindreframerpackages/
